# Phase 7.1 — DB package init
from .models import (
    Base,
    User,
    ChatSession,
    ChatMessage,
    AuditLog,
    QueryFeedback,
    DocumentAccess,
    init_db,
    get_db,
)
from .auth_service import (
    authenticate_user,
    create_user,
    create_access_token,
    create_refresh_token,
    decode_token,
    hash_password,
    verify_password,
    get_user_by_id,
    get_user_by_email,
    get_user_by_username,
)
from .dependencies import (
    get_current_user,
    get_current_user_optional,
    require_admin,
    require_hr_admin,
    require_any,
    require_role,
)

__all__ = [
    "Base",
    "User",
    "ChatSession",
    "ChatMessage",
    "AuditLog",
    "QueryFeedback",
    "DocumentAccess",
    "init_db",
    "get_db",
    "authenticate_user",
    "create_user",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "hash_password",
    "verify_password",
    "get_user_by_id",
    "get_user_by_email",
    "get_user_by_username",
    "get_current_user",
    "get_current_user_optional",
    "require_admin",
    "require_hr_admin",
    "require_any",
    "require_role",
]
